services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - .:/app
    environment:
      - ENV=${ENV:-local}
    container_name: ${CONTAINER_NAME:-gcs-app}
    networks:
      - gcs_net

networks:
  gcs_net:
    name: ${CONTAINER_NAME}_net
