name: CI/CD GCS - Deploy 

on:
  push:
    branches:
      - homolog
      - main

jobs:
  deploy-homolog:
    if: github.ref == 'refs/heads/homolog'
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Homologação
        run: |
          cd ~/homolog/GCS
          git pull origin homolog
          docker-compose down
          docker-compose up -d --build

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Produção
        run: |
          cd ~/prod/GCS
          git pull origin main
          docker-compose down
          docker-compose up -d --build
