name: CI/CD GCS - Deploy

on:
  push:
    branches:
      - homolog

jobs:
  deploy-homolog:
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Homologação
        run: |
          cd ~/homolog/GCS
          echo ">>> Limpando arquivos não versionados..."
          git restore .
          git clean -fd
          echo ">>> Atualizando repositório..."
          git pull origin homolog
          echo ">>> Removendo container antigo..."
          sudo docker compose --env-file .env down
          echo ">>> Subindo aplicação HOMOLOG com imagem nova..."
          sudo docker compose --env-file .env up -d --build
