name: CI/CD GCS - Deploy

on:
  push:
    branches:
      - homolog
      - main

jobs:
  deploy-homolog:
    if: github.ref == 'refs/heads/homolog'
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Homologação
        run: |
          cd ~/homolog/GCS

          echo ">>> Limpando conflitos locais..."
          git reset --hard HEAD
          git clean -fd -e .env -e '*.db'

          echo ">>> Atualizando repositório..."
          git pull origin homolog

          echo ">>> Removendo container antigo..."
          sudo docker compose --env-file .env down || true

          echo ">>> Subindo aplicação atualizada..."
          sudo docker compose --env-file .env up -d --build

          echo ">>> Aplicando migrações Alembic..."
          sudo docker exec tarefas-homolog alembic upgrade head