name: CI/CD GCS - Deploy

on:
  push:
    branches:
      - homolog
      - main

jobs:
  deploy-homolog:
    if: github.ref == 'refs/heads/homolog'
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Homologação
        run: |
          cd ~/homolog/GCS
          git restore docker-compose.yml
          git pull origin homolog
          sudo docker-compose down
          sudo docker-compose up -d --build

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Produção
        run: |
          cd ~/prod/GCS
          git restore docker-compose.yml
          git pull origin main
          sudo docker-compose down
          sudo docker-compose up -d --build
