name: CI/CD GCS - Deploy 

on:
  push:
    branches:
      - homolog
      - main

jobs:
  deploy-homolog:
    if: github.ref == 'refs/heads/homolog'
    runs-on: self-hosted
    steps:
      - name: Deploy automático para Homologação
        run: |
          cd ~/homolog/GCS
          git restore docker-compose.yml
          git pull origin homolog
          sudo docker compose --env-file .env down --remove-orphans
          sudo docker compose --env-file .env up -d --build
