name: CI/CD GCS - Deploy 

on:
  push:
    branches:
      - homolog
      - main

jobs:
  deploy-homolog:
    if: github.ref == 'refs/heads/homolog'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para Homologação
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOMOLOG_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ""
          script: |
            cd ~/homolog/GCS
            git pull origin homolog
            docker-compose down
            docker-compose up -d --build

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para Produção
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ""
          script: |
            cd ~/prod/GCS
            git pull origin main
            docker-compose down
            docker-compose up -d --build
